/**
 * Copyright (c) 2024 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#include "RNOH/PackageProvider.h"
// autolinking => #include "RNOHPackagesFactory.h"
#include "ReactNativeHarmony61InteropPackage.h"
#include "generated/RNOHGeneratedPackage.h"
using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  // clang-format off
  //  auto packages = createRNOHPackages(ctx); // <= autolinking
  return {
        std::make_shared<RNOHGeneratedPackage>(ctx),
     std::make_shared<ReactNativeHarmony61InteropPackage>(ctx)
  };  
    
    
    //  std::vector<std::shared_ptr<Package>> packages;
    //  packages.push_back(std::make_shared<RNOHGeneratedPackage>(ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
    //  packages.push_back(std::make_shared<ReactNativeHarmony61InteropPackage>(ctx));
    //    packages.push_back(std::make_shared<ExitAppPackage>(ctx));
    //  // clang-format on
    //  return packages;
}